### ISSUE TITLE
Make fail. r2.1.1

### ISSUE THREAD

**Issue by manlug** [lksj/einstein-puzzle#3]
Hello,
I try to make release 2.1.1 and not work.
I install libsdl-dev but not work.
My enviroment is Ubuntu 16.04 64 bits
Thanks for you time.
`
einstein-puzzle-2.1.1$ make
g++ -pipe -Wall`sdl-config --cflags`-DPREFIX=L\"/usr/local\"  -c puzgen.cpp
/bin/sh: 1: sdl-config: not found
In file included from puzgen.h:8:0,
                 from puzgen.cpp:6:
iconset.h:5:21: fatal error: SDL/SDL.h: No existe el archivo o el directorio
compilation terminated.
Makefile:46: fallo en las instrucciones para el objetivo 'puzgen.o'
make: *** [puzgen.o] Error 1
`

**Comment by lksj** [comment]
Hello.
Thank for your interest.

Why not use package from repository?
http://packages.ubuntu.com/xenial/einstein
Building from source in Ubuntu is not easy way.
Ubuntu is package-based distributive.
You will need create package for Ubuntu.

I can help you build program, but I can't help you creating ubuntu-package.
The best way: install package from repository.

If you still want to try to build from source ...
OK.

You need install follow packages:
libsdl1.2-dev
libsdl-mixer1.2-dev
libsdl-ttf2.0-dev
zlib1g-dev
with dependencies.

Then check that all files found.
In you case SDL.h not found.
Make sure for this file exist and sdl-config output correct result.

Run `sdl-config --prefix`
This output path to sdl library.

Run `sdl-config --cflags`
This output options for compiler.

Run `sdl-config --libs`
This output options for linker.

Make sure for all options in Makefile is correct.

**Comment by manlug** [comment]
Thank you for your answer.
My problema with Ubuntu and Einstein is the resolution for screen. 
When I set high resolution, Einstein or Ubuntu crash.
I probe your v2.0 for this raison.

I tell you if I can fix it.

A greeting

**Comment by lksj** [comment]
What is the resolution you set?
I will try to reproduce the problem.

Also, I ask you to run the program from the terminal and to show here output after crash.
If crash in fullscreen mode, try run game in window mode. Uncheck option in Menu -> Options -> Run in fullscreen mode.

**Comment by manlug** [comment]
Hi, my problem is solved.
I changed conexion the vga to hdmi.

A greeting.
